// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:percept/models/app_settings.dart';
import 'package:percept/models/assessment_result.dart';
import 'package:percept/models/case_progress.dart';
import 'package:percept/models/completion_record.dart';
import 'package:percept/models/daily_mission_item.dart';
import 'package:percept/models/dimension_scores.dart';
import 'package:percept/models/progress_entry.dart';
import 'package:percept/models/saved_card.dart';
import 'package:percept/models/streak_record.dart';
import 'package:percept/models/user_profile.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(AssessmentResultAdapter());
    registerAdapter(CaseProgressAdapter());
    registerAdapter(CompletionRecordAdapter());
    registerAdapter(DailyMissionItemAdapter());
    registerAdapter(DimensionScoresAdapter());
    registerAdapter(ProgressEntryAdapter());
    registerAdapter(SavedCardAdapter());
    registerAdapter(StreakRecordAdapter());
    registerAdapter(UserProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(AssessmentResultAdapter());
    registerAdapter(CaseProgressAdapter());
    registerAdapter(CompletionRecordAdapter());
    registerAdapter(DailyMissionItemAdapter());
    registerAdapter(DimensionScoresAdapter());
    registerAdapter(ProgressEntryAdapter());
    registerAdapter(SavedCardAdapter());
    registerAdapter(StreakRecordAdapter());
    registerAdapter(UserProfileAdapter());
  }
}
